package com.aurionpro.loanapp.property;

public enum EligibilityCriteria {

	AGE,
    NATIONALITY,
    EMPLOYMENT_TYPE,
    WORK_EXPERIENCE,
    CREDIT_SCORE,
    DEBT_TO_INCOME_RATIO,
    EMPLOYER_CATEGORY,
    EXISTING_LOAN_OBLIGATIONS,
    GEOGRAPHICAL_LOCATION,
    CUSTOMER_PROFILE,
    EMPLOYMENT_STABILITY,
    VALID_ID_PROOF,
    EDUCATIONAL_QUALIFICATION,
    ASSET_OWNERSHIP,
    LOAN_COLLATERAL_TYPE,
    RELATIONSHIP_WITH_LENDER,
    REPAYMENT_CAPACITY,
    REQUIRED_AMOUNT,    
    ANNUAL_INCOME,
    OCCUPATION,
    REASON,
    TENURE
    
}
